# --------------------------------------------------------------------------------------
# List of Modules
# By default, all integrations are disabled. You must enable them manually as needed.
# Requires a restart to take effect.
# All modules are required (except SkinsRestorer) for CozySkills.
# --------------------------------------------------------------------------------------
modules:
  sqlite: true
  mysql: true
  worldguard: false
  vault: false
  realistic_seasons: false
  skins_restorer: false
  better_model: false
  hologram_lib: false
  ultimate_advancement: false
  ray_trace: false
  uni_dialogs: false

# --------------------------------------------------------------------------------------
# MySQL Database
# If you are using any vSkills, this is required.
# Requires a restart to take effect.
# --------------------------------------------------------------------------------------
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: vlib_db

# --------------------------------------------------------------------------------------
# Color-Coded Console Messages
# --------------------------------------------------------------------------------------
console-colors:
  info: "<green>"
  warning: "<yellow>"
  severe: "<red>"

# --------------------------------------------------------------------------------------
# Message Prefixes
# --------------------------------------------------------------------------------------
message-prefixes:
  info: "<white> <#77DD77>"
  notification: "<white> <#FFFACD>"
  warning: "<white> <#FFD580>"
  severe: "<white> <#FF6961>"
  broadcast: "<white> <gradient:#EBD197:#B48811>"